/**
 * Greenfield Partners — Portfolio Company Data
 * Single source of truth for all portfolio companies.
 * Assets live in:
 *   Favicons  → assets/Favicons/<name>
 *   BG images → assets/portfolio bgs/<name>
 */

const PORTFOLIO = [

    // ── Currently on Dashboard ─────────────────────────────────────────────

    {
        id: 'vast',
        name: 'VAST Data',
        sector: 'AI Infrastructure',
        category: 'ai-infra',
        description: 'The Data Platform Company for the AI Era',
        round: 'Led Series B',
        year: 2019,
        featured: true,                 // spans 2-col in bento grid
        favicon: 'assets/Favicons/vast favicon.png',
        bg: 'assets/portfolio bgs/vast bg.png',
    },
    {
        id: 'coralogix',
        name: 'Coralogix',
        sector: 'IT Infrastructure',
        category: 'it-infra',
        description: 'Observability and Security that Scale with You',
        round: 'Led Series B',
        year: 2021,
        featured: false,
        favicon: 'assets/Coralogix/cropped-cropped-favicon-192x192.png',
        bg: 'assets/portfolio bgs/coralogix bg.png',
    },
    {
        id: 'exodigo',
        name: 'Exodigo',
        sector: 'Deep Tech',
        category: 'deep-tech',
        description: 'Non-Intrusive Underground Mapping',
        round: 'Led Series A',
        year: 2023,
        featured: false,
        favicon: 'assets/Favicons/exodigo favicon.png',
        bg: 'assets/portfolio bgs/exodigo bg.png',
    },
    {
        id: 'robco',
        name: 'RobCo',
        sector: 'Deep Tech',
        category: 'deep-tech',
        description: 'The Robot Company centered on Software and AI',
        round: 'Series C',
        year: 2026,
        featured: false,
        favicon: 'assets/Favicons/robco favicon.png',
        bg: 'assets/portfolio bgs/robco bg.png',
    },
    {
        id: 'torq',
        name: 'Torq',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'The AI-Native Hyperautomation Platform for Security Teams',
        round: 'Led Series B',
        year: 2023,
        featured: false,
        favicon: 'assets/Favicons/torq favicon.png',
        bg: 'assets/portfolio bgs/torq bg.png',
    },
    {
        id: 'aai',
        name: 'AAI',
        sector: 'AI Infrastructure',
        category: 'aai',
        description: 'Cracking the Code<br>of Superintelligence',
        round: 'Series A',
        year: 2025,
        featured: false,
        favicon: 'assets/Favicons/AAI favicon.png',
        bg: 'assets/portfolio bgs/aai bg.png',
    },
    {
        id: 'silverfort',
        name: 'Silverfort',
        sector: 'Cybersecurity',
        category: 'cybersecurity',
        description: 'Where Identity Security has Never Gone Before',
        round: 'Led Series C',
        year: 2022,
        featured: false,
        favicon: 'assets/Favicons/silverfort favicon.png',
        bg: 'assets/portfolio bgs/silverfort bg.png',
    },

    // ── Staged — ready to pull into dashboard ─────────────────────────────

    {
        id: 'bigpanda',
        name: 'BigPanda',
        sector: 'IT Infrastructure',
        category: 'it-infra',
        description: 'Event Correlation & Automation Platform',
        round: 'Led Series B',
        year: 2017,
        featured: false,
        favicon: 'assets/Favicons/bigpanda favicon.png',
        bg: 'assets/portfolio bgs/Bigpanda bg.png',
    },
    {
        id: 'capitolis',
        name: 'Capitolis',
        sector: 'Fintech',
        category: 'fintech',
        description: 'Safer and more Vibrant Capital Markets',
        round: 'Series D',
        year: 2022,
        featured: false,
        favicon: 'assets/Favicons/Capitolis favicon.png',
        bg: 'assets/portfolio bgs/Capitolis bg.png',
    },
    {
        id: 'goodship',
        name: 'GoodShip',
        sector: 'Vertical AI',
        category: 'vertical-ai',
        description: 'AI Freight Orchestration & Procurement',
        round: 'Led Series B',
        year: 2025,
        featured: false,
        favicon: 'assets/Favicons/Goodship favicon.png',
        bg: 'assets/portfolio bgs/Goodship bg.png',
    },
    {
        id: 'regulus',
        name: 'Regulus',
        sector: 'Defense',
        category: 'defense',
        description: 'Next Generation Counter Unmanned Systems',
        round: 'Led Series C',
        year: 2025,
        featured: false,
        favicon: 'assets/Favicons/regulus favicon.png',
        bg: 'assets/portfolio bgs/regulus bg.png',
    },
    {
        id: 'commcrete',
        name: 'Commcrete',
        sector: 'Defense',
        category: 'defense',
        description: 'Connect Beyond Borders',
        round: 'Led Series A',
        year: 2025,
        featured: false,
        favicon: 'assets/Favicons/Commcrete.png',
        bg: 'assets/portfolio bgs/Commcrete.png',
    },

];
